### ISSUE TITLE
メッセージを一括取得できるようにする

### ISSUE THREAD

**Issue by sizumita** [machikado-network/tubuyaita#4]
要件

 - GET `/api/v1/messages` で取得可能
 - ペジネーションあり（?after=id hashで、ない場合は最新30くらい）で
 - 時系列順に新しい方から取得する
 - `Tubuyaita.Message.Message` に、 もしある場合はアカウント情報とsignを含める

```ts
interface UserMessage extends Message {
    userInfo?: {
        data: string
        sign: string
    }
}
```
みたいな。
signはbinaryを`Base.encode16!/1`でエンコードしたやつ

**Comment by tignear** [comment]
ページネーションの仕様が普通にまずそう(リクエストの間に新しい投稿が追加されたときの挙動が

**Comment by sizumita** [comment]
確かに。after idとかの方が良さそう

**Comment by tignear** [comment]
ok

**Comment by tignear** [comment]
いやokではないな。メッセージが消えてたときにページネーション崩壊しそう(idは時系列に関する情報を持たないため)

**Comment by sizumita** [comment]
じゃあ時刻で行こう！

**Comment by sizumita** [comment]
いや、同じ時刻もあり得なくないから困ったな

**Comment by tignear** [comment]
ありがちなのはlink headerに前のページを取得するURLをつけておいてそのパラメータに透過的なトークンをつけとく(これが例えばtimestampとidを取り出せる何がであれば良い)あるいはidに時刻要素を入れる

**Comment by sizumita** [comment]
timestampもprimary keyにするのはなし？
なしなら前者が良さそう

**Comment by tignear** [comment]
ほい。(言っといてなんだけどこれめんどくせーんだ…)

**Comment by sizumita** [comment]
わかる、クッソめんどくさそう
やはり他の方法を考えるべきかも

**Comment by sizumita** [comment]
結論: contents_hashとtimestampどちらとも使って検索することに。さらにlimitで取得個数を指定できるようにする（最大100?）

**Comment by tignear** [comment]
これ書きながら気が付いたんだけどtimestampってユーザーの自称だから普通に途中に入るじゃん(問題かといわれたらまぁ微妙だけど

**Comment by sizumita** [comment]
バリデーションした方がいいかも

**Comment by tignear** [comment]
どうやって?

**Comment by tignear** [comment]
あとそれ意味ある?()

**Comment by sizumita** [comment]
例えば1番最近のtimestampとの誤差を考えるとか？
やる意味はある気がする
